In [35]:
# Modules
import os
import csv
import pandas as pd

In [36]:
# Set path for file

file_one = "RVCT_Sites.txt"

In [37]:
# Open the CSV TXT file

file_one_df = pd.read_csv(file_one, encoding="ISO-8859-1")
file_one_df

            TABLE
0       Ft Rucker
1              AL
2        Training
3           CONUS
4        Air RVCT
5              30
6           WAATS
7              AZ
8        Training
9           CONUS
10       Air RVCT
11             30
12          EAATS
13             PA
14       Training
15          CONUS
16       Air RVCT
17             30
18      Ft Carson
19             CO
20        FORSCOM
21          CONUS
22       Air RVCT
23             30
24     Hunter AAF
25             GA
26        FORSCOM
27          CONUS
28       Air RVCT
29             30
..            ...
537      ST Croix
538            VI
539          ARNG
540         CONUS
541   Ground RVCT
542            36
543          JBER
544            AK
545          ARNG
546        OCONUS
547   Ground RVCT
548            36
549  FT Juan Muna
550            GU
551          ARNG
552        OCONUS
553   Ground RVCT
554            36
555       Kapolei
556            HI
557          ARNG
558        OCONUS
559   Ground RVCT
560            36
561       Salinas
562            PR
563          ARNG
564        OCONUS
565   Ground RVCT
566            36

[567 rows x 1 columns]

In [38]:
from split import partition

In [39]:


with open('RVCT_Sites.txt', 'r') as f:
  reader = csv.reader(f)
  your_list = list(reader)

print(your_list)

[['TABLE'], ['Ft Rucker'], ['AL'], ['Training'], ['CONUS'], ['Air RVCT'], ['30'], ['WAATS'], ['AZ'], ['Training'], ['CONUS'], ['Air RVCT'], ['30'], ['EAATS'], ['PA'], ['Training'], ['CONUS'], ['Air RVCT'], ['30'], ['Ft Carson'], ['CO'], ['FORSCOM'], ['CONUS'], ['Air RVCT'], ['30'], ['Hunter AAF'], ['GA'], ['FORSCOM'], ['CONUS'], ['Air RVCT'], ['30'], ['Ft Riley'], ['KS'], ['FORSCOM'], ['CONUS'], ['Air RVCT'], ['30'], ['Ft Bragg'], ['NC'], ['FORSCOM'], ['CONUS'], ['Air RVCT'], ['30'], ['Ft Drum'], ['NY'], ['FORSCOM'], ['CONUS'], ['Air RVCT'], ['30'], ['Ft Bliss'], ['TX'], ['FORSCOM'], ['CONUS'], ['Air RVCT'], ['30'], ['Ft Hood'], ['TX'], ['FORSCOM'], ['CONUS'], ['Air RVCT'], ['30'], ['JBLM'], ['WA'], ['FORSCOM'], ['CONUS'], ['Air RVCT'], ['30'], ['Ft Wainwright'], ['AK'], ['USARPAC'], ['OCONUS'], ['Air RVCT'], ['30'], ['Wheeler AAF'], ['HI'], ['USARPAC'], ['OCONUS'], ['Air RVCT'], ['30'], ['Camp Humphreys'], ['Korea'], ['USARPAC'], ['OCONUS'], ['Air RVCT'], ['30'], ['USAREUR'], ['USAREUR'], ['USAREUR'], ['OCONUS'], ['Air RVCT'], ['30'], ['TABLE'], ['Gowen Field'], ['ID'], ['ARNG'], ['CONUS'], ['Air RVCT'], ['30'], ['Shelbyville'], ['IN'], ['ARNG'], ['CONUS'], ['Air RVCT'], ['30'], ['Hammond'], ['LA'], ['ARNG'], ['CONUS'], ['Air RVCT'], ['30'], ['Camp Edwards'], ['MA'], ['ARNG'], ['CONUS'], ['Air RVCT'], ['30'], ['Grand Island'], ['NE'], ['ARNG'], ['CONUS'], ['Air RVCT'], ['30'], ['Ft Indian Town Gap'], ['PA'], ['ARNG'], ['CONUS'], ['Air RVCT'], ['30'], ['TBD'], ['TBD'], ['ARNG'], ['CONUS'], ['Air RVCT'], ['30'], ['TBD'], ['TBD'], ['ARNG'], ['CONUS'], ['Air RVCT'], ['30'], ['TABLE'], ['Fort Benning'], ['GA'], ['TRADOC'], ['CONUS'], ['Ground RVCT'], ['144'], ['Fort Gordon'], ['GA'], ['TRADOC'], ['CONUS'], ['Ground RVCT'], ['36'], ['Fort Leonard Wood'], ['MO'], ['TRADOC'], ['CONUS'], ['Ground RVCT'], ['72'], ['Fort Lee'], ['VA'], ['TRADOC'], ['CONUS'], ['Ground RVCT'], ['72'], ['Fort Campbell SOF'], ['KY'], ['SOF'], ['CONUS'], ['Ground RVCT'], ['36'], ['Fort Bragg SOF'], ['NC'], ['SOF'], ['CONUS'], ['Ground RVCT'], ['36'], ['Fort Carson'], ['CO'], ['FORSCOM'], ['CONUS'], ['Ground RVCT'], ['144'], ['Fort Stewart'], ['GA'], ['FORSCOM'], ['CONUS'], ['Ground RVCT'], ['144'], ['Fort Riley'], ['KS'], ['FORSCOM'], ['CONUS'], ['Ground RVCT'], ['144'], ['Fort Campbell'], ['KY'], ['FORSCOM'], ['CONUS'], ['Ground RVCT'], ['72'], ['Fort Polk'], ['LA'], ['FORSCOM'], ['CONUS'], ['Ground RVCT'], ['36'], ['Fort Bragg'], ['NC'], ['FORSCOM'], ['CONUS'], ['Ground RVCT'], ['72'], ['Fort Drum'], ['NY'], ['FORSCOM'], ['CONUS'], ['Ground RVCT'], ['72'], ['Fort Sill'], ['OK'], ['FORSCOM'], ['CONUS'], ['Ground RVCT'], ['36'], ['Fort Bliss'], ['TX'], ['FORSCOM'], ['CONUS'], ['Ground RVCT'], ['144'], ['Fort Hood'], ['TX'], ['FORSCOM'], ['CONUS'], ['Ground RVCT'], ['144'], ['Fort Lewis'], ['WA'], ['FORSCOM'], ['CONUS'], ['Ground RVCT'], ['72'], ['Fort Richardson'], ['AK'], ['USARPAC'], ['OCONUS'], ['Ground RVCT'], ['36'], ['Fort Wainwright'], ['AK'], ['USARPAC'], ['OCONUS'], ['Ground RVCT'], ['36'], ['Schofield Barracks'], ['HI'], ['USARPAC'], ['OCONUS'], ['Ground RVCT'], ['72'], ['Camp Humphries'], ['Korea'], ['USARPAC'], ['OCONUS'], ['Ground RVCT'], ['72'], ['Graf'], ['Germany'], ['USAREUR'], ['OCONUS'], ['Ground RVCT'], ['36'], ['ARCENT'], ['Kuwait'], ['CENTCOM'], ['OCONUS'], ['Ground RVCT'], ['36'], ['TABLE'], ['Fort McClellan'], ['AL'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Camp Robertson'], ['AR'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Camp Navajo'], ['AZ'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Camp Roberts'], ['CA'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Camp Niantic'], ['CT'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Bethany Beach'], ['DE'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['District of Columbia'], ['District of Columbia'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Camp Blanding'], ['FL'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Marietta'], ['GA'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Camp Dodge'], ['IA'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Gowen Field'], ['ID'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['72'], ['Marseills'], ['IL'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Camp Atterbury'], ['IN'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Salina'], ['KS'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Greenville'], ['KY'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Camp Beauregard'], ['LA'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Bourne'], ['MA'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Reisterstown'], ['MD'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Augusta'], ['ME'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Camp Grayling'], ['MI'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Camp Ripley'], ['MN'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['72'], ['Neosho'], ['MO'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Camp Shelby'], ['MS'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['72'], ['Helena'], ['MT'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Rougemont'], ['NC'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['72'], ['Devils Lake'], ['ND'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Mead'], ['ND'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Strafford'], ['NH'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['JBMDL'], ['NJ'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Las Cruses'], ['NV'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Reno'], ['NV'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['72'], ['Cortlandt'], ['NY'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Camp Perry'], ['OH'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Braggs'], ['OK'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Warrenton'], ['OR'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Fort Indiantown Gap'], ['PA'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['72'], ['East Greenwich'], ['RI'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Eastover'], ['SC'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Sioux Falls'], ['SC'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Smyrna'], ['TN'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['72'], ['Gatesville'], ['TX'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Bluffdale'], ['UT'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['Fort Pickett'], ['VA'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['ST Croix'], ['VI'], ['ARNG'], ['CONUS'], ['Ground RVCT'], ['36'], ['JBER'], ['AK'], ['ARNG'], ['OCONUS'], ['Ground RVCT'], ['36'], ['FT Juan Muna'], ['GU'], ['ARNG'], ['OCONUS'], ['Ground RVCT'], ['36'], ['Kapolei'], ['HI'], ['ARNG'], ['OCONUS'], ['Ground RVCT'], ['36'], ['Salinas'], ['PR'], ['ARNG'], ['OCONUS'], ['Ground RVCT'], ['36']]

In [40]:
import itertools

[x for x in your_list if 'TABLE' in x]

[['TABLE'], ['TABLE'], ['TABLE'], ['TABLE']]

In [41]:
TableCount = 0

RVCT_Headers = ['TABLE', 'BASE', 'STATE', 'COMMAND', 'REGION', 'TYPE', 'QUANTITY']
RVCT_Table = []
RVCT_Base = []
RVCT_State = []
RVCT_Command = []
RVCT_Region = []
RVCT_Type = []
RVCT_Quantity = []

Field = 0
for entry in your_list:
    try:
        if 'TABLE' in entry:
            TableCount = TableCount + 1
            print(f"Table:{TableCount}:{entry}")
            Field = 0
        else:
            RVCT_Table.append(TableCount)
            Field = Field + 1
            if Field == 0: print("Lost track!")
            if Field == 1: RVCT_Base.append(entry)
            if Field == 2: RVCT_State.append(entry)
            if Field == 3: RVCT_Command.append(entry)
            if Field == 4: RVCT_Region.append(entry)
            if Field == 5: RVCT_Type.append(entry)
            if Field == 6: RVCT_Quantity.append(entry)
            if Field == 6: Field = 0
    except:
        print("bump")

Table:1:['TABLE']
Table:2:['TABLE']
Table:3:['TABLE']
Table:4:['TABLE']

In [42]:
print(RVCT_Headers)

['TABLE', 'BASE', 'STATE', 'COMMAND', 'REGION', 'TYPE', 'QUANTITY']

In [43]:
print(RVCT_Table)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]

In [44]:
print(RVCT_Base)

[['Ft Rucker'], ['WAATS'], ['EAATS'], ['Ft Carson'], ['Hunter AAF'], ['Ft Riley'], ['Ft Bragg'], ['Ft Drum'], ['Ft Bliss'], ['Ft Hood'], ['JBLM'], ['Ft Wainwright'], ['Wheeler AAF'], ['Camp Humphreys'], ['USAREUR'], ['Gowen Field'], ['Shelbyville'], ['Hammond'], ['Camp Edwards'], ['Grand Island'], ['Ft Indian Town Gap'], ['TBD'], ['TBD'], ['Fort Benning'], ['Fort Gordon'], ['Fort Leonard Wood'], ['Fort Lee'], ['Fort Campbell SOF'], ['Fort Bragg SOF'], ['Fort Carson'], ['Fort Stewart'], ['Fort Riley'], ['Fort Campbell'], ['Fort Polk'], ['Fort Bragg'], ['Fort Drum'], ['Fort Sill'], ['Fort Bliss'], ['Fort Hood'], ['Fort Lewis'], ['Fort Richardson'], ['Fort Wainwright'], ['Schofield Barracks'], ['Camp Humphries'], ['Graf'], ['ARCENT'], ['Fort McClellan'], ['Camp Robertson'], ['Camp Navajo'], ['Camp Roberts'], ['Camp Niantic'], ['Bethany Beach'], ['District of Columbia'], ['Camp Blanding'], ['Marietta'], ['Camp Dodge'], ['Gowen Field'], ['Marseills'], ['Camp Atterbury'], ['Salina'], ['Greenville'], ['Camp Beauregard'], ['Bourne'], ['Reisterstown'], ['Augusta'], ['Camp Grayling'], ['Camp Ripley'], ['Neosho'], ['Camp Shelby'], ['Helena'], ['Rougemont'], ['Devils Lake'], ['Mead'], ['Strafford'], ['JBMDL'], ['Las Cruses'], ['Reno'], ['Cortlandt'], ['Camp Perry'], ['Braggs'], ['Warrenton'], ['Fort Indiantown Gap'], ['East Greenwich'], ['Eastover'], ['Sioux Falls'], ['Smyrna'], ['Gatesville'], ['Bluffdale'], ['Fort Pickett'], ['ST Croix'], ['JBER'], ['FT Juan Muna'], ['Kapolei'], ['Salinas']]

In [45]:
print(RVCT_State)

[['AL'], ['AZ'], ['PA'], ['CO'], ['GA'], ['KS'], ['NC'], ['NY'], ['TX'], ['TX'], ['WA'], ['AK'], ['HI'], ['Korea'], ['USAREUR'], ['ID'], ['IN'], ['LA'], ['MA'], ['NE'], ['PA'], ['TBD'], ['TBD'], ['GA'], ['GA'], ['MO'], ['VA'], ['KY'], ['NC'], ['CO'], ['GA'], ['KS'], ['KY'], ['LA'], ['NC'], ['NY'], ['OK'], ['TX'], ['TX'], ['WA'], ['AK'], ['AK'], ['HI'], ['Korea'], ['Germany'], ['Kuwait'], ['AL'], ['AR'], ['AZ'], ['CA'], ['CT'], ['DE'], ['District of Columbia'], ['FL'], ['GA'], ['IA'], ['ID'], ['IL'], ['IN'], ['KS'], ['KY'], ['LA'], ['MA'], ['MD'], ['ME'], ['MI'], ['MN'], ['MO'], ['MS'], ['MT'], ['NC'], ['ND'], ['ND'], ['NH'], ['NJ'], ['NV'], ['NV'], ['NY'], ['OH'], ['OK'], ['OR'], ['PA'], ['RI'], ['SC'], ['SC'], ['TN'], ['TX'], ['UT'], ['VA'], ['VI'], ['AK'], ['GU'], ['HI'], ['PR']]

In [46]:
print(RVCT_Command)

[['Training'], ['Training'], ['Training'], ['FORSCOM'], ['FORSCOM'], ['FORSCOM'], ['FORSCOM'], ['FORSCOM'], ['FORSCOM'], ['FORSCOM'], ['FORSCOM'], ['USARPAC'], ['USARPAC'], ['USARPAC'], ['USAREUR'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['TRADOC'], ['TRADOC'], ['TRADOC'], ['TRADOC'], ['SOF'], ['SOF'], ['FORSCOM'], ['FORSCOM'], ['FORSCOM'], ['FORSCOM'], ['FORSCOM'], ['FORSCOM'], ['FORSCOM'], ['FORSCOM'], ['FORSCOM'], ['FORSCOM'], ['FORSCOM'], ['USARPAC'], ['USARPAC'], ['USARPAC'], ['USARPAC'], ['USAREUR'], ['CENTCOM'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG'], ['ARNG']]

In [47]:
print(RVCT_Region)

[['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['OCONUS'], ['OCONUS'], ['OCONUS'], ['OCONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['OCONUS'], ['OCONUS'], ['OCONUS'], ['OCONUS'], ['OCONUS'], ['OCONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['CONUS'], ['OCONUS'], ['OCONUS'], ['OCONUS'], ['OCONUS']]

In [48]:
print(RVCT_Type)

[['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Air RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT'], ['Ground RVCT']]

In [49]:
print(RVCT_Quantity)

[['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['30'], ['144'], ['36'], ['72'], ['72'], ['36'], ['36'], ['144'], ['144'], ['144'], ['72'], ['36'], ['72'], ['72'], ['36'], ['144'], ['144'], ['72'], ['36'], ['36'], ['72'], ['72'], ['36'], ['36'], ['36'], ['36'], ['36'], ['36'], ['36'], ['36'], ['36'], ['36'], ['36'], ['36'], ['72'], ['36'], ['36'], ['36'], ['36'], ['36'], ['36'], ['36'], ['36'], ['36'], ['72'], ['36'], ['72'], ['36'], ['72'], ['36'], ['36'], ['36'], ['36'], ['36'], ['72'], ['36'], ['36'], ['36'], ['36'], ['72'], ['36'], ['36'], ['36'], ['72'], ['36'], ['36'], ['36'], ['36'], ['36'], ['36'], ['36'], ['36']]

In [51]:
#RVCT_Summary_data = {"Table": [RVCT_Table], "Base": [RVCT_Base], "State": [RVCT_State], "Command": [RVCT_Command], "Region": [RVCT_Region], "Type": [RVCT_Type], "Quantity": [RVCT_Quantity]}
#RVCT_Summary_df = pd.DataFrame(RVCT_Summary_data) 
#RVCT_Summary_df

,Table,Base,State,Command,Region,Type,Quantity
0,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[[Ft Rucker], [WAATS], [EAATS], [Ft Carson], [...","[[AL], [AZ], [PA], [CO], [GA], [KS], [NC], [NY...","[[Training], [Training], [Training], [FORSCOM]...","[[CONUS], [CONUS], [CONUS], [CONUS], [CONUS], ...","[[Air RVCT], [Air RVCT], [Air RVCT], [Air RVCT...","[[30], [30], [30], [30], [30], [30], [30], [30..."

In [52]:
table_output = pd.DataFrame(RVCT_Table, columns=["Table"])
table_output.to_csv('Table_data.csv', index=False)
print(table_output)

     Table
0        1
1        1
2        1
3        1
4        1
5        1
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25       1
26       1
27       1
28       1
29       1
..     ...
534      4
535      4
536      4
537      4
538      4
539      4
540      4
541      4
542      4
543      4
544      4
545      4
546      4
547      4
548      4
549      4
550      4
551      4
552      4
553      4
554      4
555      4
556      4
557      4
558      4
559      4
560      4
561      4
562      4
563      4

[564 rows x 1 columns]

In [53]:
base_output = pd.DataFrame(RVCT_Base, columns=["Base"])
base_output.to_csv('Base_data.csv', index=False)
print(base_output)

                   Base
0             Ft Rucker
1                 WAATS
2                 EAATS
3             Ft Carson
4            Hunter AAF
5              Ft Riley
6              Ft Bragg
7               Ft Drum
8              Ft Bliss
9               Ft Hood
10                 JBLM
11        Ft Wainwright
12          Wheeler AAF
13       Camp Humphreys
14              USAREUR
15          Gowen Field
16          Shelbyville
17              Hammond
18         Camp Edwards
19         Grand Island
20   Ft Indian Town Gap
21                  TBD
22                  TBD
23         Fort Benning
24          Fort Gordon
25    Fort Leonard Wood
26             Fort Lee
27    Fort Campbell SOF
28       Fort Bragg SOF
29          Fort Carson
..                  ...
64              Augusta
65        Camp Grayling
66          Camp Ripley
67               Neosho
68          Camp Shelby
69               Helena
70            Rougemont
71          Devils Lake
72                 Mead
73            Strafford
74                JBMDL
75           Las Cruses
76                 Reno
77            Cortlandt
78           Camp Perry
79               Braggs
80            Warrenton
81  Fort Indiantown Gap
82       East Greenwich
83             Eastover
84          Sioux Falls
85               Smyrna
86           Gatesville
87            Bluffdale
88         Fort Pickett
89             ST Croix
90                 JBER
91         FT Juan Muna
92              Kapolei
93              Salinas

[94 rows x 1 columns]

In [54]:
state_output = pd.DataFrame(RVCT_State, columns=["State"])
state_output.to_csv('State_data.csv', index=False)
print(state_output)

      State
0        AL
1        AZ
2        PA
3        CO
4        GA
5        KS
6        NC
7        NY
8        TX
9        TX
10       WA
11       AK
12       HI
13    Korea
14  USAREUR
15       ID
16       IN
17       LA
18       MA
19       NE
20       PA
21      TBD
22      TBD
23       GA
24       GA
25       MO
26       VA
27       KY
28       NC
29       CO
..      ...
64       ME
65       MI
66       MN
67       MO
68       MS
69       MT
70       NC
71       ND
72       ND
73       NH
74       NJ
75       NV
76       NV
77       NY
78       OH
79       OK
80       OR
81       PA
82       RI
83       SC
84       SC
85       TN
86       TX
87       UT
88       VA
89       VI
90       AK
91       GU
92       HI
93       PR

[94 rows x 1 columns]

In [55]:
command_output = pd.DataFrame(RVCT_Command, columns=["Command"])
command_output.to_csv('Command_data.csv', index=False)
print(command_output)

     Command
0   Training
1   Training
2   Training
3    FORSCOM
4    FORSCOM
5    FORSCOM
6    FORSCOM
7    FORSCOM
8    FORSCOM
9    FORSCOM
10   FORSCOM
11   USARPAC
12   USARPAC
13   USARPAC
14   USAREUR
15      ARNG
16      ARNG
17      ARNG
18      ARNG
19      ARNG
20      ARNG
21      ARNG
22      ARNG
23    TRADOC
24    TRADOC
25    TRADOC
26    TRADOC
27       SOF
28       SOF
29   FORSCOM
..       ...
64      ARNG
65      ARNG
66      ARNG
67      ARNG
68      ARNG
69      ARNG
70      ARNG
71      ARNG
72      ARNG
73      ARNG
74      ARNG
75      ARNG
76      ARNG
77      ARNG
78      ARNG
79      ARNG
80      ARNG
81      ARNG
82      ARNG
83      ARNG
84      ARNG
85      ARNG
86      ARNG
87      ARNG
88      ARNG
89      ARNG
90      ARNG
91      ARNG
92      ARNG
93      ARNG

[94 rows x 1 columns]

In [56]:
region_output = pd.DataFrame(RVCT_Region, columns=["Region"])
region_output.to_csv('Region_data.csv', index=False)
print(region_output)

    Region
0    CONUS
1    CONUS
2    CONUS
3    CONUS
4    CONUS
5    CONUS
6    CONUS
7    CONUS
8    CONUS
9    CONUS
10   CONUS
11  OCONUS
12  OCONUS
13  OCONUS
14  OCONUS
15   CONUS
16   CONUS
17   CONUS
18   CONUS
19   CONUS
20   CONUS
21   CONUS
22   CONUS
23   CONUS
24   CONUS
25   CONUS
26   CONUS
27   CONUS
28   CONUS
29   CONUS
..     ...
64   CONUS
65   CONUS
66   CONUS
67   CONUS
68   CONUS
69   CONUS
70   CONUS
71   CONUS
72   CONUS
73   CONUS
74   CONUS
75   CONUS
76   CONUS
77   CONUS
78   CONUS
79   CONUS
80   CONUS
81   CONUS
82   CONUS
83   CONUS
84   CONUS
85   CONUS
86   CONUS
87   CONUS
88   CONUS
89   CONUS
90  OCONUS
91  OCONUS
92  OCONUS
93  OCONUS

[94 rows x 1 columns]

In [57]:
type_output = pd.DataFrame(RVCT_Type, columns=["Type"])
type_output.to_csv('Type_data.csv', index=False)
print(type_output)

           Type
0      Air RVCT
1      Air RVCT
2      Air RVCT
3      Air RVCT
4      Air RVCT
5      Air RVCT
6      Air RVCT
7      Air RVCT
8      Air RVCT
9      Air RVCT
10     Air RVCT
11     Air RVCT
12     Air RVCT
13     Air RVCT
14     Air RVCT
15     Air RVCT
16     Air RVCT
17     Air RVCT
18     Air RVCT
19     Air RVCT
20     Air RVCT
21     Air RVCT
22     Air RVCT
23  Ground RVCT
24  Ground RVCT
25  Ground RVCT
26  Ground RVCT
27  Ground RVCT
28  Ground RVCT
29  Ground RVCT
..          ...
64  Ground RVCT
65  Ground RVCT
66  Ground RVCT
67  Ground RVCT
68  Ground RVCT
69  Ground RVCT
70  Ground RVCT
71  Ground RVCT
72  Ground RVCT
73  Ground RVCT
74  Ground RVCT
75  Ground RVCT
76  Ground RVCT
77  Ground RVCT
78  Ground RVCT
79  Ground RVCT
80  Ground RVCT
81  Ground RVCT
82  Ground RVCT
83  Ground RVCT
84  Ground RVCT
85  Ground RVCT
86  Ground RVCT
87  Ground RVCT
88  Ground RVCT
89  Ground RVCT
90  Ground RVCT
91  Ground RVCT
92  Ground RVCT
93  Ground RVCT

[94 rows x 1 columns]

In [58]:
quantity_output = pd.DataFrame(RVCT_Quantity, columns=["Quantity"])
quantity_output.to_csv('Quantity_data.csv', index=False)
print(quantity_output)

   Quantity
0        30
1        30
2        30
3        30
4        30
5        30
6        30
7        30
8        30
9        30
10       30
11       30
12       30
13       30
14       30
15       30
16       30
17       30
18       30
19       30
20       30
21       30
22       30
23      144
24       36
25       72
26       72
27       36
28       36
29      144
..      ...
64       36
65       36
66       72
67       36
68       72
69       36
70       72
71       36
72       36
73       36
74       36
75       36
76       72
77       36
78       36
79       36
80       36
81       72
82       36
83       36
84       36
85       72
86       36
87       36
88       36
89       36
90       36
91       36
92       36
93       36

[94 rows x 1 columns]